"""
cased2.0 / cli
==============

    python3 -m cased [path] [options]

Four stages, each independently inspectable in the output folder:

    analyze   repo      -> story.json
    score     duration  -> score.wav + beat map
    compose   story+map -> spec.json
    render    spec      -> cased.mp4
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

from .analyze import analyze, plural
from .insight import inspect
from .compose import compose
from .directors import DIRECTORS, pick
from . import themes as themes_mod
from . import score as score_mod

HERE = Path(__file__).resolve().parent

FORMATS = {
    "16:9":  (1920, 1080, "cased"),
    "9:16":  (1080, 1920, "cased-vertical"),
    "1:1":   (1080, 1080, "cased-square"),
    "4:5":   (1080, 1350, "cased-portrait"),
}

C = {
    "dim": "\033[2m", "b": "\033[1m", "r": "\033[0m",
    "pink": "\033[95m", "cyan": "\033[96m", "green": "\033[92m",
    "red": "\033[91m", "yellow": "\033[93m",
}
if not sys.stderr.isatty() or os.environ.get("NO_COLOR"):
    C = {k: "" for k in C}


def say(msg: str, icon: str = "·") -> None:
    sys.stderr.write(f"{C['dim']}{icon}{C['r']} {msg}\n")
    sys.stderr.flush()


def head(msg: str) -> None:
    sys.stderr.write(f"\n{C['pink']}{C['b']}{msg}{C['r']}\n")
    sys.stderr.flush()


def die(msg: str, code: int = 1):
    sys.stderr.write(f"{C['red']}error:{C['r']} {msg}\n")
    raise SystemExit(code)


def preflight(need_render: bool) -> None:
    """Fail early and tell the user exactly what to install."""
    missing = []
    if need_render:
        if not shutil.which("ffmpeg"):
            missing.append("ffmpeg   -- https://ffmpeg.org/download.html")
        if not shutil.which("node"):
            missing.append("node 18+ -- https://nodejs.org")
    if missing:
        die("missing prerequisites:\n   " + "\n   ".join(missing))


# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="cased",
        description="Turn a repository into a cinematic launch film.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="directors:\n" + "\n".join(
            f"  {k:<11} {v['blurb']}" for k, v in DIRECTORS.items()),
    )
    p.add_argument("path", nargs="?", default=".", help="project directory (default: .)")
    p.add_argument("--director", "-d", choices=list(DIRECTORS),
                   help="pacing and shot grammar (default: chosen from the project)")
    p.add_argument("--theme", choices=themes_mod.names(), metavar="NAME",
                   help="palette and surface treatment; any of the "
                        f"{len(themes_mod.names())} themes works with any director "
                        "(see --list-themes)")
    p.add_argument("--duration", "-t", type=float, default=0.0,
                   help="runtime in seconds (default: 24, or 60 with --creative)")
    p.add_argument("--creative", "-c", action="store_true",
                   help="long-form mode: reads the architecture, the history and "
                        "the signature function, and cuts a detailed ~60s film")
    p.add_argument("--format", "-f", default="16:9",
                   help="16:9 | 9:16 | 1:1 | 4:5 | all (comma-separated ok)")
    p.add_argument("--quality", "-q", default="high", choices=["draft", "good", "high"])
    p.add_argument("--out", "-o", default="cased-output", help="output directory")
    p.add_argument("--seed", type=int, default=0, help="reproducibility seed")
    p.add_argument("--url", default="", help="override the project URL shown on the end card")
    p.add_argument("--tagline", default="", help="override the headline")
    p.add_argument("--no-audio", action="store_true", help="render silent")
    p.add_argument("--gif", action="store_true", help="also emit a looping GIF")
    p.add_argument("--plan-only", action="store_true",
                   help="write story.json + spec.json and stop (no render)")
    p.add_argument("--list-directors", action="store_true")
    p.add_argument("--list-themes", action="store_true",
                   help="every theme, grouped by family")
    p.add_argument("--list-graphics", action="store_true",
                   help="every graphic primitive the engine can draw")
    return p


def resolve_formats(spec: str) -> list:
    if spec.strip().lower() == "all":
        return list(FORMATS.items())
    out = []
    for token in spec.split(","):
        key = token.strip()
        if key not in FORMATS:
            die(f"unknown format {key!r}. choose from: {', '.join(FORMATS)} or 'all'")
        out.append((key, FORMATS[key]))
    return out


def write_share(outdir: Path, spec: dict) -> None:
    s = spec["share"]
    md = f"""# {spec['project']} — share kit

Generated by cased2.0 · director: **{spec['director_label']}** · seed `{spec['seed']}`

## X / Twitter

```
{s['x']}
```

## LinkedIn

```
{s['linkedin']}
```

## Hacker News

```
{s['hn']}
```

## Product Hunt tagline

```
{s['product_hunt']}
```

## Alt text (accessibility — use it)

```
{s['alt_text']}
```
"""
    (outdir / "SHARE.md").write_text(md, encoding="utf-8")


def write_plan(outdir: Path, spec: dict, story: dict) -> None:
    lines = [
        f"# {spec['project']} — edit plan", "",
        f"- **Director** {spec['director_label']} (`{spec['director']}`)",
        f"- **Runtime** {spec['duration']}s @ {spec['fps']}fps",
        f"- **Tempo** {spec['beatmap']['bpm']} BPM, {spec['beatmap']['scale']}",
        f"- **Seed** `{spec['seed']}` (same seed, same film)", "",
        "## Shot list", "",
        "| # | in | type | start | dur | content |",
        "|--:|----|------|------:|----:|---------|",
    ]
    for i, sh in enumerate(spec["shots"], 1):
        d = sh.get("data", {})
        blurb = (d.get("text") or d.get("label") or d.get("path")
                 or d.get("title") or d.get("name") or "")
        blurb = str(blurb).replace("|", "\\|")[:58]
        lines.append(
            f"| {i} | {sh['in']} | {sh['type']} | {sh['start']:.2f}s "
            f"| {sh['dur']:.2f}s | {blurb} |")
    st = story["stats"]
    lines += ["", "## What the analyzer found", "",
              f"- {plural(st.get('loc', 0), 'line')} across "
              f"{plural(st.get('files', 0), 'file')}",
              f"- {plural(st.get('commits', 0), 'commit')}, "
              f"{plural(st.get('contributors', 0), 'contributor')}",
              f"- Languages: " + ", ".join(
                  f"{l['name']} {l['share']}%" for l in story.get("languages", [])[:5]),
              ""]
    (outdir / "PLAN.md").write_text("\n".join(lines), encoding="utf-8")


def run_render(spec_path: Path, out_video: Path, audio: Path | None,
               quality: str, poster: Path | None, gif: Path | None) -> None:
    cmd = [
        "node", str(HERE / "engine" / "render.mjs"),
        "--spec", str(spec_path), "--out", str(out_video), "--quality", quality,
    ]
    if audio:
        cmd += ["--audio", str(audio)]
    if poster:
        cmd += ["--poster", str(poster)]
    if gif:
        cmd += ["--gif", str(gif)]
    r = subprocess.run(cmd)
    if r.returncode != 0:
        die("render failed (see output above)", r.returncode)


def _list_graphics() -> int:
    """Count the engine's primitives by reading stage.html's own registries.

    Hand-maintained counts drift the moment someone adds a shot. These are
    parsed out of the source of truth instead.
    """
    import re
    stage = (HERE / "engine" / "stage.html").read_text(encoding="utf-8")

    def registry(pattern):
        return sorted(set(re.findall(pattern, stage, re.M)))

    shots = registry(r"^BUILD\.([a-zA-Z_][\w]*) =")
    beds = registry(r"^([a-z_][a-z0-9_]*):\s*`")
    def names_in(const):
        m = re.search(const + r"\s*=\s*\[(.*?)\]", stage, re.S)
        return sorted(set(re.findall(r"'([^']+)'", m.group(1)))) if m else []
    ins = names_in("const IN_NAMES")
    cams = names_in("const CAM_NAMES")
    fx = registry(r"^([a-z][a-zA-Z0-9_]*)\(c, t, p, th, W, H\)")

    groups = [
        ("themes", themes_mod.names()),
        ("shot types", shots),
        ("background beds", beds),
        ("overlay layers", fx),
        ("transitions", ins),
        ("camera moves", cams),
        ("directors", list(DIRECTORS)),
    ]
    total = 0
    for label, items in groups:
        total += len(items)
        print(f"\n{C['pink']}{C['b']}{label}{C['r']}  {C['dim']}{len(items)}{C['r']}")
        line = "  "
        for it in items:
            if len(line) + len(it) > 76:
                print(line); line = "  "
            line += it + "  "
        if line.strip():
            print(line)
    print(f"\n{C['b']}{total} distinct graphics primitives{C['r']}")
    print(f"{C['dim']}every theme composes with every director, so the "
          f"look-and-pacing space alone is {len(themes_mod.names())} x "
          f"{len(DIRECTORS)} = {len(themes_mod.names()) * len(DIRECTORS)}{C['r']}\n")
    return 0


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)

    if args.list_directors:
        for k, v in DIRECTORS.items():
            print(f"{C['b']}{k}{C['r']}  {C['dim']}theme: {v['theme']}{C['r']}\n  {v['blurb']}\n")
        return 0

    if args.list_themes:
        fams = themes_mod.families()
        for fam, names in fams.items():
            print(f"\n{C['pink']}{C['b']}{fam}{C['r']}")
            for nm in names:
                t = themes_mod.get(nm)
                flags = []
                if t["scanlines"]:
                    flags.append("scanlines")
                if t["letterbox"]:
                    flags.append("letterbox")
                print(f"  {C['b']}{nm:<18}{C['r']} {t['bg']} {t['accent']} {t['accent2']}"
                      f"  {C['dim']}bed:{t['bed']}  {' '.join(flags)}{C['r']}")
        print(f"\n{len(themes_mod.names())} themes\n")
        return 0

    if args.list_graphics:
        return _list_graphics()

    root = Path(args.path).resolve()
    if not root.is_dir():
        die(f"{root} is not a directory")

    # Creative mode is long-form by default; 24s cannot carry its shot list.
    duration = args.duration or (60.0 if args.creative else 24.0)
    if args.creative and duration < 40:
        say(f"creative mode at {duration:g}s will drop most structural beats; "
            f"40s or more is where it earns its keep", "!")

    preflight(need_render=not args.plan_only)

    outdir = Path(args.out).resolve()
    outdir.mkdir(parents=True, exist_ok=True)
    t_start = time.time()

    # --- 1. analyze -------------------------------------------------------
    head("1/4  reading the repository")
    story_obj = analyze(root, seed=args.seed, url=args.url)
    if args.tagline:
        story_obj.tagline = args.tagline
        story_obj.description = args.tagline
    story = json.loads(story_obj.to_json())
    (outdir / "story.json").write_text(story_obj.to_json(), encoding="utf-8")
    st = story["stats"]
    say(f"{story['name']} — {plural(st.get('loc', 0), 'line')}, "
        f"{plural(st.get('files', 0), 'file')}, "
        f"{plural(st.get('commits', 0), 'commit')}", "✓")
    say(f"hero language: {story.get('hero_language') or 'n/a'}; "
        f"code moments: {len(story.get('code_moments', []))}", "✓")

    insight = None
    if args.creative:
        ins_obj = inspect(root, story)
        insight = json.loads(ins_obj.to_json())
        (outdir / "insight.json").write_text(ins_obj.to_json(), encoding="utf-8")
        say(f"{len(insight['modules'])} modules, {len(insight['edges'])} imports; "
            f"hub: {insight['hub'] or 'n/a'}", "✓")
        if insight.get("signature"):
            sg = insight["signature"]
            say(f"signature function: {sg['name']}() in {sg['module']} "
                f"({sg['lines']} lines)", "✓")
        if insight.get("techniques"):
            say("techniques: " + ", ".join(t["name"] for t in insight["techniques"][:4]), "✓")

    dname, d = pick(args.director or ("creative" if args.creative else None),
                    story.get("kind", "project"))
    say(f"director: {C['b']}{d['label']}{C['r']} — {d['blurb']}", "✓")
    say(f"theme: {C['b']}{args.theme or d['theme']}{C['r']}", "✓")

    # --- 2. score ---------------------------------------------------------
    head("2/4  writing the score")
    wav = outdir / "score.wav"
    if args.no_audio:
        # Still need the beat map: the edit is cut to it either way.
        _, beatmap = score_mod.compose_score(duration, d["mood"],
                                             args.seed or story["seed"], 0.0)
        wav = None
        say("silent render — beat map still drives the cuts", "✓")
    else:
        beatmap = score_mod.render(duration, wav, d["mood"],
                                   args.seed or story["seed"], d["intensity"])
        say(f"{beatmap['bpm']} BPM {beatmap['scale']}, "
            f"{len(beatmap['sections'])} sections -> {wav.name}", "✓")

    # --- 3. compose -------------------------------------------------------
    head("3/4  cutting the edit")
    formats = resolve_formats(args.format)
    specs = []
    for key, (w, h, stem) in formats:
        spec = compose(story, beatmap, duration, dname, w, h,
                       args.seed or story["seed"], insight=insight,
                       theme=args.theme)
        sp = outdir / (f"spec-{stem}.json" if len(formats) > 1 else "spec.json")
        sp.write_text(json.dumps(spec, indent=2), encoding="utf-8")
        specs.append((key, w, h, stem, sp, spec))
    base = specs[0][5]
    say(f"{len(base['shots'])} shots over {duration:g}s "
        f"({base['mode']} mode), cuts snapped to the {beatmap['bpm']} BPM grid", "✓")
    write_plan(outdir, base, story)
    write_share(outdir, base)
    say("PLAN.md + SHARE.md written", "✓")

    if args.plan_only:
        head(f"done (plan only) — {outdir}")
        return 0

    # --- 4. render --------------------------------------------------------
    head("4/4  rendering")
    for i, (key, w, h, stem, sp, spec) in enumerate(specs):
        video = outdir / f"{stem}.mp4"
        poster = (outdir / "poster.png") if i == 0 else None
        gif = (outdir / f"{stem}.gif") if (args.gif and i == 0) else None
        say(f"{key} -> {video.name} ({w}x{h})", "→")
        run_render(sp, video, wav, args.quality, poster, gif)

    # --- summary ----------------------------------------------------------
    dt = time.time() - t_start
    head(f"done in {dt:.0f}s")
    for f in sorted(outdir.iterdir()):
        if f.is_file():
            size = f.stat().st_size
            unit = f"{size/1_048_576:.1f} MB" if size > 1_048_576 else f"{size/1024:.0f} KB"
            sys.stderr.write(f"  {C['green']}{f.name:<28}{C['r']} {C['dim']}{unit}{C['r']}\n")
    sys.stderr.write(f"\n{C['dim']}share copy is in {outdir.name}/SHARE.md{C['r']}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
