#!/usr/bin/env python3
"""
Write the site's data files from the Python modules that define them:

    docs/assets/themes.json     <- cased/themes.py
    docs/assets/directors.json  <- cased/directors.py

The theme gallery and the browser Make flow read both tables as JSON. themes
.json used to be generated by hand, which meant adding a theme to the Python
module left the site showing the old set with no warning. These make the
Python modules the one source, and `--check` fails CI the moment a file drifts.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "docs" / "assets"

sys.path.insert(0, str(ROOT))
from cased import themes as themes_mod        # noqa: E402
from cased.directors import DIRECTORS         # noqa: E402


def build_themes() -> str:
    """The palette plus the grouping and mood the site labels each tile with."""
    out = {}
    for name, t in themes_mod.THEMES.items():
        spec = themes_mod.to_spec(name)
        spec["mood"] = t["mood"]
        spec["family"] = t["family"]
        out[name] = spec
    return json.dumps(out, indent=1) + "\n"


def build_directors() -> str:
    """Pacing and shot grammar, exactly as the composer reads it."""
    return json.dumps(DIRECTORS, indent=1) + "\n"


FILES = [
    ("themes.json", build_themes, "cased/themes.py", lambda: len(themes_mod.THEMES), "themes"),
    ("directors.json", build_directors, "cased/directors.py", lambda: len(DIRECTORS), "directors"),
]


def main() -> int:
    check = "--check" in sys.argv
    stale = 0
    for fname, build, src, count, noun in FILES:
        out = ASSETS / fname
        text = build()
        rel = out.relative_to(ROOT)
        if check:
            have = out.read_text(encoding="utf-8") if out.exists() else ""
            if have != text:
                print(f"{rel} is stale -- run scripts/sync_data.py")
                stale += 1
            else:
                print(f"{rel} matches {src} ({count()} {noun})")
            continue
        out.write_text(text, encoding="utf-8")
        print(f"wrote {rel} ({count()} {noun})")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
