#!/usr/bin/env python3
"""
Write docs/assets/themes.json from cased/themes.py.

The site's theme gallery and the browser Make flow both read the palette table
as JSON. It used to be generated by hand, which meant adding a theme to the
Python module left the site showing the old set with no warning. This makes
themes.py the one source and `--check` fails CI the moment the JSON drifts.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "assets" / "themes.json"

sys.path.insert(0, str(ROOT))
from cased import themes as themes_mod  # noqa: E402


def build() -> str:
    """The palette plus the grouping and mood the site labels each tile with."""
    out = {}
    for name, t in themes_mod.THEMES.items():
        spec = themes_mod.to_spec(name)
        spec["mood"] = t["mood"]
        spec["family"] = t["family"]
        out[name] = spec
    return json.dumps(out, indent=1) + "\n"


def main() -> int:
    text = build()
    if "--check" in sys.argv:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != text:
            print(f"{OUT.relative_to(ROOT)} is stale -- run scripts/sync_themes.py")
            return 1
        print(f"{OUT.relative_to(ROOT)} matches cased/themes.py "
              f"({len(themes_mod.THEMES)} themes)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(themes_mod.THEMES)} themes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
